[package]
name = "rcs-parser"
version = "0.1.0"
authors = ["David Seres <dseres001@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "6.1.*"
jemallocator = "0.3.*"
